name: Main Preview

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: v21.1.0
      - name: Install dependencies
        run: yarn --prefer-offline
      - name: Run Prettier
        run: yarn run format
  build:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - uses: actions/checkout@v2
        name: Check out repository
      - uses: actions/setup-node@v1
        name: Set up Node.js
        with:
          node-version: v21.1.0
